apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-refresher-deployment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-refresher
  template:
    metadata:
      labels:
        app: traffic-refresher
    spec:
      containers:
      - name: traffic-refresher
        image: gcr.io/aurora-alarm/traffic-refresher
        env:
          - name: DATEX_USERNAME
            valueFrom:
              secretKeyRef:
                name: datex-secret
                key: username
          - name: DATEX_PASSWORD
            valueFrom:
              secretKeyRef:
                name: datex-secret
                key: password
      serviceAccount: backend-worker




